server:
  port: 8111
spring:
  application:
    name: hungvo-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: admin-page
          uri: lb://BAR
          predicates:
            - Path=/admin/**, /system/**, /api/**, /access-denied
        - id: user-page
          uri: http://127.0.0.1:3000
          predicates:
            - Path=/**
          filters:
            - RewritePath=/react/(?<segment>.*), /${segment}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
